// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type procxdpCommKey struct {
	_    structs.HostLayout
	Name [16]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	procxdpMapAllowedPorts   = "allowed_ports"
	procxdpMapBlockedPorts   = "blocked_ports"
	procxdpProgFilterPackets = "filter_packets"
	procxdpProgTrackListen   = "track_listen"
)

// loadProcxdp returns the embedded CollectionSpec for procxdp.
func loadProcxdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcxdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load procxdp: %w", err)
	}

	return spec, err
}

// loadProcxdpObjects loads procxdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*procxdpObjects
//	*procxdpPrograms
//	*procxdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcxdpObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcxdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// procxdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procxdpSpecs struct {
	procxdpProgramSpecs
	procxdpMapSpecs
	procxdpVariableSpecs
}

// procxdpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procxdpProgramSpecs struct {
	FilterPackets *ebpf.ProgramSpec `ebpf:"filter_packets"`
	TrackListen   *ebpf.ProgramSpec `ebpf:"track_listen"`
}

// procxdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procxdpMapSpecs struct {
	AllowedPorts *ebpf.MapSpec `ebpf:"allowed_ports"`
	BlockedPorts *ebpf.MapSpec `ebpf:"blocked_ports"`
}

// procxdpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type procxdpVariableSpecs struct {
}

// procxdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type procxdpObjects struct {
	procxdpPrograms
	procxdpMaps
	procxdpVariables
}

func (o *procxdpObjects) Close() error {
	return _ProcxdpClose(
		&o.procxdpPrograms,
		&o.procxdpMaps,
	)
}

// procxdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type procxdpMaps struct {
	AllowedPorts *ebpf.Map `ebpf:"allowed_ports"`
	BlockedPorts *ebpf.Map `ebpf:"blocked_ports"`
}

func (m *procxdpMaps) Close() error {
	return _ProcxdpClose(
		m.AllowedPorts,
		m.BlockedPorts,
	)
}

// procxdpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type procxdpVariables struct {
}

// procxdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcxdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type procxdpPrograms struct {
	FilterPackets *ebpf.Program `ebpf:"filter_packets"`
	TrackListen   *ebpf.Program `ebpf:"track_listen"`
}

func (p *procxdpPrograms) Close() error {
	return _ProcxdpClose(
		p.FilterPackets,
		p.TrackListen,
	)
}

func _ProcxdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed procxdp_bpfeb.o
var _ProcxdpBytes []byte
